In [1]:
%matplotlib inline

#### Pytorch是什么？
基于Python的科学计算包，服务于以下两种场景：
- 作为NumPy的替代品，可以使用GPU的强大计算能力
- 提供最大的灵活性和高速的深度学习研究平台

#### Tensor
在Pytorch中Tensors可以使用GPU进行计算

In [2]:
from __future__ import print_function
import torch

x = torch.empty(5, 3) # 创建一个未初始化的5x3矩阵
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
x = torch.rand(5,3) # 创建一个随机初始化的5x3矩阵
print(x)

tensor([[0.6280, 0.2065, 0.7060],
        [0.9418, 0.5482, 0.6151],
        [0.5951, 0.5639, 0.9356],
        [0.6442, 0.8648, 0.1971],
        [0.3621, 0.0483, 0.6312]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long) # 创建一个5x3的零矩阵，数据类型为long
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3]) # 直接从数据创建张量
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5,3,dtype=torch.double) # new_* 方法根据现有张量的属性创建新张量
print(x)

x = torch.randn_like(x, dtype=torch.float) # 重写数据类型
print(x) # 输出结果与上面相同尺寸，但数据类型不同

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.1185, -0.0552,  1.3971],
        [ 1.1347, -0.1404,  1.7929],
        [-0.1461, -0.5637,  0.0044],
        [-1.3583, -1.7542,  0.1996],
        [-0.7303, -1.6010,  1.4021]])


使用size方法于NumPy的shape属性返回的相同，张量也支持shape属性

In [7]:
print(x.size())

torch.Size([5, 3])


"torch.size"返回值是tuple类型，支持tuple类型的所有操作。

#### 加法运算

In [8]:
y = torch.rand(5,3)
print(x+y)

tensor([[-0.4668,  0.5723,  2.1845],
        [ 2.0237,  0.3674,  2.6866],
        [ 0.7605, -0.5560,  0.5933],
        [-0.4212, -1.5621,  0.4491],
        [ 0.0706, -0.8108,  2.1094]])


In [9]:
print(torch.add(x,y))

tensor([[-0.4668,  0.5723,  2.1845],
        [ 2.0237,  0.3674,  2.6866],
        [ 0.7605, -0.5560,  0.5933],
        [-0.4212, -1.5621,  0.4491],
        [ 0.0706, -0.8108,  2.1094]])


In [10]:
result = torch.empty(5,3) # 可以通过out参数指定输出张量
torch.add(x,y,out = result)
print(result)

tensor([[-0.4668,  0.5723,  2.1845],
        [ 2.0237,  0.3674,  2.6866],
        [ 0.7605, -0.5560,  0.5933],
        [-0.4212, -1.5621,  0.4491],
        [ 0.0706, -0.8108,  2.1094]])


In [11]:
y.add_(x) # 这个语句会改变y
print(y)

tensor([[-0.4668,  0.5723,  2.1845],
        [ 2.0237,  0.3674,  2.6866],
        [ 0.7605, -0.5560,  0.5933],
        [-0.4212, -1.5621,  0.4491],
        [ 0.0706, -0.8108,  2.1094]])


任何以`_`结尾的操作都会用结果替换原变量。例如：`x.copy_(y)`,`x.t_()`都会改变x

In [12]:
print(x[:,1]) # 取第二列所有元素

tensor([-0.0552, -0.1404, -0.5637, -1.7542, -1.6010])


`torch.view`可以改变张量的维度和大小

In [13]:
x = torch.randn(4,4) 
y = x.view(16) # 改变维度为1x16
z = x.view(-1,8) # -1表示自适应计算该维度大小，这里变为2x8
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
x = torch.randn(1)  # 创建一个标量张量
print(x)
print(x.item())  # 使用item()获取张量的值

tensor([0.1451])
0.145149827003479


#### NumPy转换
Torch Tensor与NumPy数组共享底层内存地址，修改一个会导致另一个的变化。
将一个Torch Tensor转换为NumPy数组

In [15]:
a = torch.ones(5) # 创建一个长度为5的全1张量
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy() # 将Torch张量转换为NumPy数组
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add(1)    
print(a)
print(b)  

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [18]:
import numpy as np
a = np.ones(5)  # 创建一个长度为5的NumPy数组
b = torch.from_numpy(a)  # 将NumPy数组转换为Torch张量
np.add(a,1,out=a)  # NumPy数组加1
print(a)
print(b)  # Torch张量也会改变

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


所有的Tensor类型默认都是基于CPU，CharTensor类型不支持到NumPy的转换。

CUDA张量使用`.to`方法可以将Tensor移动到任何设备中

In [19]:
# is_available()函数可以检查CUDA是否可用
#`torch.device`对象表示我们想要将张量存储在哪个设备上

if torch.cuda.is_available():
    device = torch.decvice("cuda")         # 一个CUDA设备对象
    y = torch.ones_like(x, device= device)   # 直接创建一个CUDA张量
    x = x.to(device)                          # 或者使用`.to`方法将张量移动到CUDA设备上
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))         # 使用`.to`方法将张量移动到CPU并更改数据类型
