#### PyTorch基础：张量

In [1]:
import torch
import numpy as np

torch.__version__

'2.8.0'

#### 张量（Tensor）
Tensor是PyTorch里面基础的运算单位，与Numpy的ndarray相同，都表示的是一个多维的矩阵。与ndarray的最大区别就是，PyTorch的Tensor可以在GPU上运行，而Numpy的ndarray只能在CPU上运行，在GPU上运行大大加快了运算速度。

下面我们生成一个简单的张量。

In [2]:
x = torch.rand(2, 3) # 生成一个2行3列的随机张量
x

tensor([[0.7641, 0.2276, 0.7648],
        [0.0197, 0.9050, 0.5619]])

In [3]:
print(x.shape)  # 输出张量的形状
print(x.size())  # 输出张量的形状，等价于x.shape

torch.Size([2, 3])
torch.Size([2, 3])


张量（tensor）是一个定义在一些张量空间和一些对偶空间的笛卡尔积上的多重线性映射，其坐标是n维空间内，有n个分量的一种量，其中每个分量都是坐标的函数。而在坐标变换时，这些分量也依照某些规则作线性变换。r称为该张量的秩或阶（与矩阵的秩和阶均无关系）。

In [4]:
y = torch.rand(2,3,4,5)  # 生成一个2x3x4x5的随机张量
print(y.size())  # 输出张量的形状
y

torch.Size([2, 3, 4, 5])


tensor([[[[0.9627, 0.1141, 0.8486, 0.8356, 0.8587],
          [0.5418, 0.8174, 0.6005, 0.0965, 0.8303],
          [0.1391, 0.3076, 0.7895, 0.6155, 0.6628],
          [0.3231, 0.5223, 0.5444, 0.8989, 0.4116]],

         [[0.3931, 0.8159, 0.7216, 0.1741, 0.6903],
          [0.8077, 0.0810, 0.6242, 0.7658, 0.6776],
          [0.9745, 0.5951, 0.5533, 0.6079, 0.3307],
          [0.7373, 0.2226, 0.8817, 0.2303, 0.9428]],

         [[0.9879, 0.7443, 0.7721, 0.0296, 0.6624],
          [0.3084, 0.1969, 0.3693, 0.1537, 0.1498],
          [0.1185, 0.4198, 0.9368, 0.7222, 0.7226],
          [0.6109, 0.5037, 0.3604, 0.0631, 0.8926]]],


        [[[0.1489, 0.3011, 0.9575, 0.2981, 0.1518],
          [0.9751, 0.5308, 0.8342, 0.2133, 0.4051],
          [0.9869, 0.1186, 0.4335, 0.0045, 0.6526],
          [0.3630, 0.0477, 0.9128, 0.6366, 0.6189]],

         [[0.1986, 0.3052, 0.9606, 0.3996, 0.4836],
          [0.4570, 0.1778, 0.9988, 0.1658, 0.7575],
          [0.7717, 0.8957, 0.0051, 0.0272, 0.0636],
  

在同构的意义下，第零阶张量（r=0）为标量（Scalar），第一阶张量（r=1）为向量（Vector），第二阶张量（r=2）则为矩阵（Matrix），第三阶以上统称为多维张量。

In [5]:
scalar = torch.tensor(5)  # 标量
print(scalar)
scalar.size()

tensor(5)


torch.Size([])

 对于标量，我们可以直接用`.item()`从中取出其对应的python对象的数值。

In [6]:
scalar.item()  # 取出标量的数值

5

特别的：如果张量中只有一个元素的tensor也可以调用`tensor.item`方法。

In [7]:
tensor = torch.tensor([42])  # 只有一个元素的张量
print(tensor)
tensor.size()


tensor([42])


torch.Size([1])

In [8]:
tensor.item()  # 取出张量中唯一元素的数值

42

#### 基本类型

Tensor的基本数据类型有五种：

- 32位浮点型：`torch.FloatTensor`（默认）
- 64位整型：`torch.LongTensor`
- 32位整型：`torch.IntTensor`
- 16位整型：`torch.ShortTensor`
- 64位浮点型：`torch.DoubleTensor`

除以上数字类型外，还有`byte`和 `chart`型

In [9]:
long = tensor.long()  # 转换为长整型张量
long

tensor([42])

In [10]:
half = tensor.half()  # 转换为半精度浮点型张量
half

tensor([42.], dtype=torch.float16)

In [11]:
int_t = tensor.int()  # 转换为整型张量
int_t

tensor([42], dtype=torch.int32)

In [12]:
flo = tensor.float()  # 转换为单精度浮点型张量
flo

tensor([42.])

In [13]:
short = tensor.short()  # 转换为短整型张量
short

tensor([42], dtype=torch.int16)

In [14]:
ch = tensor.char()  # 转换为字符型张量
ch

tensor([42], dtype=torch.int8)

In [15]:
bt = tensor.byte()  # 转换为字节型张量
bt

tensor([42], dtype=torch.uint8)

#### Numpy转换
使用numpy方法把Tensor转换为ndarray

In [16]:
a = torch.randn((3, 2))
numpy_a = a.numpy()  # 使用numpy方法把Tensor转换为ndarray
print(numpy_a)

[[ 0.13345253 -0.22973956]
 [ 0.60256785  1.9548762 ]
 [-1.1720358   0.61694145]]


numpy转化为Tensor

In [17]:
torch_a = torch.from_numpy(numpy_a)  # 使用from_numpy方法把ndarray转换为Tensor
torch_a

tensor([[ 0.1335, -0.2297],
        [ 0.6026,  1.9549],
        [-1.1720,  0.6169]])

Tensor和Numpy对象共享内存，所以他们之间转换得很快，而且几乎不会消耗什么资源。但这也意味着，如果其中一个变了，另一个也会随之改变。

#### 设备间转换

一般情况下可以使用`.cuda`方法将`tensor`移动到`gpu`，这步操作需要cuda设备支持。

In [18]:
cpu_a = torch.rand(4, 3)  # 创建一个在CPU上的张量
cpu_a.type()

'torch.FloatTensor'

In [20]:
# gpu_a = cpu_a.cuda()  # 把张量移动到GPU上 # 不使用于macOS
# gpu_a.type()

if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

gpu_a = cpu_a.to(device)
print(f"张量设备: {gpu_a.device}")
print(f"张量类型: {gpu_a.type()}")

张量设备: mps:0
张量类型: torch.mps.FloatTensor


In [21]:
# 使用.cuda方法把张量从GPU移动回CPU
cpu_b = gpu_a.cpu()
cpu_b.type()

'torch.FloatTensor'

如果我们有多GPU的情况，可以使用to方法来确定使用哪个设备。

In [22]:
# 使用torch.cuda.is_available()来检查当前系统是否有可用的CUDA设备
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

gpu_b = cpu_b.to(device)  # 把张量移动到指定设备上
gpu_b.type()

cpu


'torch.FloatTensor'

#### 初始化


In [23]:
rnd = torch.rand(5, 3)  # 生成一个5x3的随机张量
rnd

tensor([[0.2474, 0.2836, 0.1611],
        [0.8726, 0.2797, 0.6178],
        [0.3280, 0.7531, 0.0917],
        [0.6948, 0.9211, 0.6420],
        [0.5221, 0.6147, 0.1789]])

In [24]:
one = torch.ones(2, 2) # 生成一个2x2的全1张量
one

tensor([[1., 1.],
        [1., 1.]])

In [25]:
zero = torch.zeros(2, 2)  # 生成一个2x2的全0张量
zero

tensor([[0., 0.],
        [0., 0.]])

In [26]:
eye = torch.eye(2, 2) # 生成一个2x2的单位矩阵
eye

tensor([[1., 0.],
        [0., 1.]])

#### 常用方法

PyTorch中对张量的操作api和NumPy非常相似，如果熟悉NumPy中的操作，那么他们二者基本是一致的。

In [27]:
x = torch.randn(3, 3)
print(x)

tensor([[ 1.2978, -1.1216, -1.3120],
        [-0.6444, -0.7867, -1.3209],
        [ 0.0276,  1.8775,  1.3607]])


In [28]:
max_value, max_idx = torch.max(x, dim = 1)  # 按行取最大值及其索引
print(max_value, max_idx)

tensor([ 1.2978, -0.6444,  1.8775]) tensor([0, 0, 1])


In [29]:
sum_x = torch.sum(x, dim = 0)  # 按列求和
print(sum_x)

tensor([ 0.6811, -0.0308, -1.2722])


In [30]:
y = torch.randn(3, 3)
z = x + y  # 张量加法
print(z)

tensor([[ 2.5258, -1.7859, -0.3966],
        [-0.7582,  0.1773, -1.6449],
        [-0.3545,  4.2611,  2.3116]])


In [31]:
x.add_(y)  # 张量加法，结果存储在x中
print(x)

tensor([[ 2.5258, -1.7859, -0.3966],
        [-0.7582,  0.1773, -1.6449],
        [-0.3545,  4.2611,  2.3116]])


### 使用PyTorch计算梯度数值

PyTorch的`Autograd`模块实现了深度学习的算法中的向传播求导数，在张量（Tensor类）上的所有操作，`Autograd`都能为他们自动提供微分，简化了手动计算导数的复杂过程。

要想通过Tensor类本身就支持了使用autograd功能，只需要设置`.requires_grad = True`

Variable类中的`grad`和`grad_fn`属性已经整合进入了Tensor类中。

#### Autograd
在张量创建时，通过设置`requires_grad`表示为`True`来告诉PyTorch需要对该张量进行自动求导，PyTorch会记录该张量的每一步操作历史并自动计算。

In [32]:
x = torch.rand(5, 5, requires_grad=True)
print(x)

tensor([[0.6070, 0.8575, 0.5657, 0.3939, 0.3134],
        [0.3983, 0.8798, 0.3192, 0.5927, 0.4837],
        [0.1083, 0.6101, 0.1454, 0.4246, 0.3370],
        [0.5790, 0.2759, 0.5966, 0.7167, 0.4238],
        [0.0926, 0.0801, 0.5709, 0.7173, 0.6505]], requires_grad=True)


In [33]:
y = torch.rand(5, 5, requires_grad = True)
y

tensor([[0.1099, 0.7146, 0.8885, 0.8838, 0.5491],
        [0.6069, 0.0146, 0.2674, 0.3327, 0.7821],
        [0.2905, 0.6269, 0.1861, 0.6863, 0.7453],
        [0.5733, 0.8268, 0.8817, 0.7041, 0.6073],
        [0.6877, 0.2613, 0.7635, 0.2653, 0.6642]], requires_grad=True)

PyTorch会自动追踪和记录对与张量的所有操作，当计算完成后调用`.backward()`方法自动计算梯度并且将计算结果保存到`grad`属性中。

In [34]:
z = torch.sum(x + y) # 计算x和y的和，并求和得到标量z
z

tensor(25.6598, grad_fn=<SumBackward0>)

在张量进行操作之后，`grad_fn`已经被赋予了一个新的函数，这个函数引用了一个创建了这个Tensor类的Function对象。Tensor和Function互相连接生成了一个非循环图，它记录并且编码了完整的计算历史。每个张量都有一个`.grad_fn`属性，如果这个张量时用户手动创建的，那么这个张量的`grad_fn`是`None`。

#### 简单的自动求导

In [35]:
z.backward() # 对标量z进行反向传播，计算梯度
print(x.grad, y.grad)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


如果Tensor类表示的是一个标量，则不需要为`backward()`指定任何参数，但是如果它有更多的元素，则需要指定一个`gradient`参数，它是形状匹配的张量。以上的`z.backward()`相当于是`z.backward(torch.tensor(1.))`的简写。这种参数常出现在图像分类中的单标签分类，输出一个标量代表图像的标签。

#### 复杂的自动求导

In [36]:
x = torch.rand(5, 5, requires_grad = True)
y = torch.rand(5, 5, requires_grad = True)
z = x ** 2 + y ** 3
z

tensor([[0.8791, 1.4388, 1.2485, 1.0066, 1.5183],
        [0.8075, 0.7772, 0.1792, 0.4368, 1.1118],
        [0.2393, 0.4436, 0.3406, 0.5281, 0.4258],
        [0.0288, 0.2033, 0.8205, 0.2889, 0.0615],
        [0.6016, 1.0619, 0.1828, 0.7919, 0.2525]], grad_fn=<AddBackward0>)

In [37]:
# 对张量z进行反向传播，传入与z形状相同的全1张量 
# 我们的返回值不是一个标量，所以需要输入一个大小相同的张量作为参数
z.backward(torch.ones_like(x))  
print(x.grad)



tensor([[1.8742, 1.5366, 1.9541, 1.8168, 1.9006],
        [1.7382, 1.7374, 0.6855, 1.3084, 1.5167],
        [0.5984, 1.3275, 1.1492, 1.3208, 1.2971],
        [0.3341, 0.8847, 1.7039, 1.0452, 0.2984],
        [1.5370, 1.0643, 0.8282, 1.6255, 0.9354]])


我们可以使用`with torch.no_grad()`上下文管理器临时禁制对已设置`requires_grad = True`的张量进行自动求导。这个方法在测试集计算准确率的时候会经常用到。

例如:

In [39]:
with torch.no_grad():
    print((x + y*2).requires_grad)

False


使用`.no_grad()`进行嵌套后，代码不会跟踪历史记录，也就是说保存的这部分记录会减少内存的使用量并且会加快少许的运算速度。

#### Autograd过程解析

为了说明PyTorch的自动求导原理，我们来尝试分析一下PyTorch的源代码，虽然PyTorch的Tensor和TensorBase都是使用CPP来实现的，但是可以使用一些Python的一些方法查看这些对象在Python的属性和状态。Python的`dir()`返回参数的属性，方法列表。`z`是一个Tensor变量。

In [40]:
dir(z)

['H',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__re

返回很多，我们直接排除掉一些Python中特殊方法（以__开头和结束的）和私有方法（以_开头的），直接看几个比较主要的属性:`.is_leaf()`：记录是否是叶子节点。通过这个属性来确定这个变量的类型。

在官方文档中所说的“graph leaves”，“leaf variables”，都是指像`x`，`y`这样的手动创建的、而非运算得到的变量，这些变量称为创建变量。像`z`这样的，是通过计算后得到的结果称为结果变量。

一个变量是创建变量还是结果变量是通过`.is_leaf`来获取的。

In [41]:
print("x.is_leaf = " + str(x.is_leaf))
print("z.is_leaf = " + str(z.is_leaf))

x.is_leaf = True
z.is_leaf = False


`x`是手动创建的，没有通过计算，所以被认为是一个叶子节点，也就是一个创建变量。而`z`是通过`x`与`y`的一系列计算得到的，所以不是叶子节点，也就是变量结果。

为什么我们执行`z.backword()`方法会更新`x.grad()`和`y.grad`呢？

`.grad_fn`属性记录的就是这部分操作，虽然`.backward()`方法也是CPP实现的，但是可以通过Python来进行简单的探索。

`grad_fn`：记录并编码了完整的计算历史

In [42]:
z.grad_fn

`grad_fn`是一个`AddBackward0`类型的变量，`AddBackward0`这个类也是用CPP来写的，但是我们从名字里就能够大概知道，它是加法（ADD）的反向传播（Backward）。

`next_function`就是`grad_fn`的精华

In [43]:
dir(z.grad_fn)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_input_metadata',
 '_register_hook_dict',
 '_saved_alpha',
 '_sequence_nr',
 '_set_sequence_nr',
 'metadata',
 'name',
 'next_functions',
 'register_hook',
 'register_prehook',
 'requires_grad']

In [45]:
z.grad_fn.next_functions

((<PowBackward0 at 0x105430eb0>, 0), (<PowBackward0 at 0x105430640>, 0))

`next_function`是一个tuple of tuple of PowBackward0 and int.

**为什么是两个tuple？**

因为我们的操作是`z = x**2 + y**3`。刚才的`AddBackward0`是相加，而前面的操作是乘方`PowBackward0`。tuple第一个元素就是x相关的操作记录。

In [46]:
xg = z.grad_fn.next_functions[0][0]
dir(xg)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_input_metadata',
 '_raw_saved_self',
 '_register_hook_dict',
 '_saved_exponent',
 '_saved_self',
 '_sequence_nr',
 '_set_sequence_nr',
 'metadata',
 'name',
 'next_functions',
 'register_hook',
 'register_prehook',
 'requires_grad']

In [47]:
x_leaf = xg.next_functions[0][0]
type(x_leaf)

AccumulateGrad

在PyTorch的反向图计算中，`AccumulateGrad`类型代表的就是叶子节点类型，也就是计算图终止节点。`AccumulateGrad`类中有一个`.variable`属性指向叶子节点。

In [48]:
x_leaf.variable

tensor([[0.9371, 0.7683, 0.9770, 0.9084, 0.9503],
        [0.8691, 0.8687, 0.3428, 0.6542, 0.7584],
        [0.2992, 0.6637, 0.5746, 0.6604, 0.6486],
        [0.1671, 0.4424, 0.8520, 0.5226, 0.1492],
        [0.7685, 0.5322, 0.4141, 0.8128, 0.4677]], requires_grad=True)

这个`.variable`属性就是我们的生成的变量`x`

In [49]:
print("x_leaf.variable的id:" + str(id(x_leaf.variable)))
print("x的id:" + str(id(x)))

x_leaf.variable的id:5020535280
x的id:5020535280


In [50]:
assert(id(x_leaf.variable)) == id(x)

这样整个规程就很清晰了：

1. 当我们执行`z.backward()`的时候。这个操作将调用z里边的`grad_fn`这个属性，执行求导操作。
2. 这个操作将遍历`grad_fn`的`next_functions`,然后分别取出里边的Function(AccumulatedGrad)，执行求导操作。这部分是一个递归的过程，直到最后类型为叶子节点。
3. 计算出结果以后，将结果保存到他们对应的`variable`这个变量所引用的对象（x和y）的`grad`这个属性里面。
4. 求导结束。所有的叶节点的`grad`变量都得到了相应的更新。

最终当我们执行完`c.backward()`之后，a和b里面的grad值就得到了更新。

#### 扩展Autograd

如果需要自定义autograd扩展新功能，就需要扩展Function类。因为Function使用autograd来计算结果和梯度，并对操作历史进行编码。在Function类中最重要的方法就是`forward()`和`backward()`，他们分别代表了前向传播和反向传播。

一个自定义的Function需要以下三种方法：

- `__init__(optional)`：如果这个操作需要额外的参数，则需要定义这个Function的构造函数，不需要的话可以忽略。
- `forward()`：执行前向传播的计算代码。
- `backward()`：反向传播时梯度计算的代码。参数的个数和`forward`返回值的个数一样，每个参数代表传回到此操作的梯度。

In [51]:
from torch.autograd.function import Function 

class MulConstant(Function):
    @staticmethod
    def forward(ctx, tensor, constant):
        ctx.constant = constant    # 保存常量以便在反向传播中使用
        return tensor * constant
    
    @staticmethod
    def backward(ctx, grad_output):
        return grad_output, None # 返回梯度和None，因为constant不是张量

In [52]:
a = torch.rand(3, 3, requires_grad = True)
b = MulConstant.apply(a, 5) 
print("a" + str(a))
print("b" + str(b))

atensor([[0.2810, 0.8864, 0.7907],
        [0.0418, 0.9751, 0.9946],
        [0.4780, 0.8575, 0.1317]], requires_grad=True)
btensor([[1.4051, 4.4319, 3.9535],
        [0.2090, 4.8756, 4.9731],
        [2.3900, 4.2875, 0.6586]], grad_fn=<MulConstantBackward>)


反向传播，返回值不是标量，所以`backward`方法需要参数

In [53]:
b.backward(torch.ones_like(a)) 

In [54]:
a.grad

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])